<MyRoot>:
    spoken_word: spoken_word
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Say something and it will be diplayed here"
            font_size: 30
            color: 0, 0.62, 0.96

        Label:
            id: spoken_word
            text: "_"
            font_size: 30

        Button:
            text: "Listen"
            font_size: 15
            on_press: root.listen()